-- v1
CREATE TABLE IF NOT EXISTS challenges (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, `value` VARBINARY(128) NOT NULL, created_at DATETIME(6) NOT NULL, expires_at DATETIME(6) NOT NULL, unused BOOLEAN NOT NULL);
ALTER TABLE challenges ADD CONSTRAINT challenges_value_unique_idx UNIQUE (`value`);