-- V1
CREATE TABLE IF NOT EXISTS challenges (id BIGSERIAL PRIMARY KEY, "value" bytea NOT NULL, created_at TIMESTAMP NOT NULL, expires_at TIMESTAMP NOT NULL, unused BOOLEAN NOT NULL);
ALTER TABLE challenges ADD CONSTRAINT challenges_value_unique_idx UNIQUE ("value");
CREATE SEQUENCE IF NOT EXISTS challenges_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;